---
title: "p8105_hw2_rz2570"
author: "Ruilian Zhang"
date: "10/2/2021"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
```

# Problem 1

```{r}
# read and clean Mr. Trash Wheel data
trash_wheel_df = read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "Mr. Trash Wheel") %>% 
  janitor::clean_names() %>% 
  select(-starts_with("x")) %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls = round(sports_balls))
```

```{r}
# read and clean precipitation data for 2018 and 2019
precipitation_2018 = read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "2018 Precipitation", range = "A2:B14") %>% 
  janitor::clean_names() %>%
  drop_na() %>% 
  rename(total_precipitation = total) %>% 
  mutate(year = 2018) %>% 
  relocate(year)

precipitation_2019 = read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "2019 Precipitation", range = "A2:B14") %>% 
  janitor::clean_names() %>%
  drop_na() %>% 
  rename(total_precipitation = total) %>% 
  mutate(year = 2019) %>% 
  relocate(year)

# combine precipitation datasets and convert month to a character variable
precipitation = bind_rows(precipitation_2018, precipitation_2019) %>% 
  mutate(month = month.name[month])
```


